import { drizzle } from "drizzle-orm/node-postgres";
import pg from "pg";
import * as schema from "@shared/schema";

const { Pool } = pg;

if (!process.env.DATABASE_URL) {
  throw new Error(
    "DATABASE_URL must be set. Did you forget to provision a database?",
  );
}

// Strip any `sslmode` query-param from the URL so pg-connection-string does
// not emit a security warning about ambiguous SSL mode aliases (prefer /
// require / verify-ca → verify-full).  We set the SSL behaviour explicitly
// via the `ssl` Pool option instead, which is the correct way to control it
// going forward (pg@9 / pg-connection-string@3 compatibility).
function stripSslMode(url: string): string {
  try {
    const u = new URL(url);
    u.searchParams.delete("sslmode");
    return u.toString();
  } catch {
    // Fallback regex strip if URL() can't parse a postgres:// scheme on older runtimes
    return url.replace(/([?&])sslmode=[^&]*(&|$)/, (_m, pre, post) =>
      post === "&" ? pre : ""
    );
  }
}

const connectionString = stripSslMode(process.env.DATABASE_URL);

// SSL policy for the database connection.
//
// - Development: the DB is reached over Replit's internal network via an
//   endpoint that does not offer TLS (the DATABASE_URL carries
//   `sslmode=disable`), so SSL stays off here intentionally. Forcing TLS in
//   dev would break the local connection.
// - Production: require TLS AND validate the server certificate. Replit's
//   managed Postgres presents a publicly-trusted certificate, so full
//   verification works out of the box. This closes the previous gap where
//   `rejectUnauthorized: false` accepted ANY certificate (that is weaker than
//   `verify-full`, despite what the old comment claimed).
//
// Escape hatch: if DATABASE_URL is ever pointed at a provider that presents a
// private/self-signed certificate, set DATABASE_SSL_REJECT_UNAUTHORIZED=false
// as a deliberate, documented downgrade — do not edit this file to weaken it.
function buildSslConfig(): false | { rejectUnauthorized: boolean } {
  if (process.env.NODE_ENV !== "production") return false;
  const allowUnverified =
    process.env.DATABASE_SSL_REJECT_UNAUTHORIZED === "false";
  return { rejectUnauthorized: !allowUnverified };
}

export const pool = new Pool({
  connectionString,
  ssl: buildSslConfig(),
});

export const db = drizzle(pool, { schema });
