// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/banxico-dashboard/DarkPremium.tsx": () => import("../components/mockups/banxico-dashboard/DarkPremium.tsx"),
  "./components/mockups/banxico-dashboard/ExecutiveLight.tsx": () => import("../components/mockups/banxico-dashboard/ExecutiveLight.tsx"),
  "./components/mockups/banxico-dashboard/ModernGlass.tsx": () => import("../components/mockups/banxico-dashboard/ModernGlass.tsx")
};
